# Generated by Django 4.1.3 on 2022-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patata', '0002_alter_videojuego_pegi'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='url_p',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='url_v',
            field=models.TextField(default=''),
        ),
    ]
