# Generated by Django 4.1.3 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patata', '0003_plataforma_url_p_videojuego_url_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='fecha_salida',
            field=models.IntegerField(),
        ),
    ]
